# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies if needed
RUN apk add --no-cache build-base linux-headers

WORKDIR /app

# Copy dependency definitions and lock file
COPY pyproject.toml uv.lock /app/

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Copy project files
COPY . /app

# Default command
CMD ["python", "mcp_server.py"]
